[build]
target = "riscv32imac-unknown-none-elf"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-Tdefmt.x",
]

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c6 --log-format defmt"

[env]
DEFMT_LOG = "info"

[unstable]
build-std = ["alloc", "core"]